[package]
name = "cam-distort"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
numpy = "0.26"
rayon = "1.11.0"
